### PR TITLE
limit scope of nginx ingress

### PR DESCRIPTION
**Pull request by samlesu**
This was causing random HTTP Gateway errors (502) when doing HTTP requests to the backend.

### CODE REVIEW

**Comment by GuillaumeCisco** [comment]
Can we have detailed information about that please?

**Comment by samlesu** [comment]
When using skaffold, the pod `nginx-ingress-controller` of a peer was not limited to a namespace. It seems it was redirecting requests to backends of different nodes. It was causing some random 502 HTTP Gateway errors when querying the backend.

According to the nginx-ingress documentation (https://github.com/helm/charts/tree/master/stable/nginx-ingress), this can be solved by setting the variable `controller.scope.enabled` to true.

**Comment by ClementGautier** [comment]
@GuillaumeCisco As we deploy one reverse proxy per namespace it has to look for ingresses only in its namespace (and by default it looks for ingresses on all namespaces and you randomly got 502s depending on the nginx reponding to your request).

**Comment by GuillaumeCisco** [comment]
Tell me if I understand this correctly:
Without `controller.scope.enabled`, the peer from an organization can redirect http traffic to a backend server from another organization?

**Comment by ClementGautier** [comment]
@GuillaumeCisco yup exactly

**Pull request merged**
