### PR TITLE
chaincode: support local filepath for chaincode source code (in addition to archive URL)

### PR DESCRIPTION
**Pull request by AurelienGasser**
The network currently downloads the chaincode source code from the public internet on each startup.

This PR allows developers to instruct hlf-k8s to fetch the chaincode source code from a local folder.

This can be useful to test local chaincode changes. This also allows developers to start the network without an internet acccess.

### CODE REVIEW

**Comment by AurelienGasser** [comment]
Could someone please test this on Mac with Docker Desktop ?

I tested it on minikube.

For easy testing, you can just change the `src` of the first peer to point to a local folder, and keep the second peer pointing to the archive URL.

Then check `chaincode-install`` logs for both peers: they should both correctly install the chaincode.

**Comment by samlesu** [comment]
I will test it on Docker Desktop for Mac.

@AurelienGasser we could update the skaffold file used for development purposes to use by default a local chaincode folder?

**Comment by AurelienGasser** [comment]
> we could update the skaffold file used for development purposes to use by default a local chaincode folder?

I don't think there's a way to do that currently, since there's no way to expand `$SUBSTRA_PATH` in the skaffold file, and each developer has a different `SUBSTRA_PATH`.

**Comment by AurelienGasser** [comment]
@Kelvin-M or @samlesu, could you please tell me how to share a folder with the k8s cluster on Docker for Mac? I'd like to put a line in the readme like I did for minikube!

**Comment by Kelvin-M** [comment]
@AurelienGasser  
In the docker for mac parameters :)
image

**Comment by Kelvin-M** [comment]
@AurelienGasser `helm` has been updated you should use now just `helm init` instead `helm init --client-only`

**Comment by Kelvin-M** [comment]
```
$ helm init --client-only
Error: unknown flag: --client-only
The command "helm init --client-only" failed and exited with 1 during .
```

**Comment by AurelienGasser** [comment]
@Kelvin-M https://github.com/SubstraFoundation/hlf-k8s/pull/15

**Pull request merged**
