### PR TITLE
Delete unused files

### PR DESCRIPTION
**Pull request by AurelienGasser**

### CODE REVIEW

**Review by inalgnu — DISMISSED** [review]

**Comment by Kelvin-M** [comment]
It looks like https://github.com/SubstraFoundation/hlf-k8s/blob/master/images/hlf-k8s/Dockerfile#L21-L24 and https://github.com/SubstraFoundation/hlf-k8s/blob/master/images/hlf-k8s/setup-hfc-binaries.sh are useless too :)

**Review by ClementGautier — DISMISSED** [review]

**Comment by Kelvin-M** [comment]
`.env` file is useless too :)

**Comment by AurelienGasser** [comment]
@Kelvin-M done

**Review by Kelvin-M — APPROVED** [review]
Good job !

**Pull request merged**
