### PR TITLE
Extract values for skaffold

### PR DESCRIPTION
**Pull request by Kelvin-M**
In order to have a simpler skaffold file and add the possibility to deploy with helm only, we extract helm values from skaffold file into separate values files.

@natct10 Do we need to update the documentation for that part ?

### CODE REVIEW

**Review by AurelienGasser — CHANGES_REQUESTED** [review]
Nice work!

I think we could make a few improvements:

- Name the values file `org-X-peer-Y` instead of `peer-Y-org-X`  (descending hierarchy)
- Make the files/folder names consistent by renaming the `4-orgs-policy-any` values folder to match the skaffold file:
  - values folder: `4-orgs-any` 
  - skaffold: `4orgs-policy-any`

Ideally we _could_ also rename the skaffold files from `skaffold-Xorgs.yaml` to `skaffold-X-orgs.yaml` (more readable and consistent with the folder names)

**Comment by AurelienGasser** [comment]
After discussion, new proposed directory structure:

 ```
/
/skaffold.yaml
/dev
/dev/values
/dev/serviceAccounts
/dev/skaffold-xxx.yaml
/dev/test-xxx.sh
```

**Comment by ClementGautier** [comment]
I would, for myself, named them like that:
```
examples/
-- 2-orgs-policy-any/
---- skaffold.yaml
---- values/
-- 4 orgs-policy-majority
...
```
examples looks more explicit that dev for me. Whatever solution you choose I'm :+1: this :100: times ;)

**Comment by Kelvin-M** [comment]
@ClementGautier Both are good for me ! 
@AurelienGasser what do you think about the skaffold files located in an examples folder ?

**Comment by AurelienGasser** [comment]
I think @ClementGautier's suggestion makes sense

We can rename `dev/` to `examples/` and leave everything as is (leave `skaffold.yaml` at the root)

I think whatever naming scheme we chose is not going to be 100% accurate/consistent here. 

If we have to choose between a `dev/` and an `examples/` folder (there's some overlap between the two), then I think `examples/` makes more sense: people looking at the repo are probably interested in examples,

I think it makes more sense to have a few dev tools/resources in `examples/` than having the examples live in a `dev/` folder

**Comment by Kelvin-M** [comment]
I made updates according your comments @AurelienGasser and @ClementGautier

**Review by AurelienGasser — APPROVED** [review]
Great work!

**Review by ClementGautier — APPROVED** [review]

**Pull request merged**
